### ISSUE TITLE
Remove `position: relative`

### ISSUE THREAD

**Issue by vabatta** [gvital3230/tailwindcss-tooltip-arrow-after#5]
Hi,

great plugin! I was using it and soon realized that the enforcing of `position: relative` is unnecessary and might conflict when used on `absolute` elements. I would leave it to the user to decide which positioning to use.

**Comment by gvital3230** [comment]
Yes, indeed, if you will use another positioned elements inside this tooltip div, it will break functionality. But the idea of this plugin was to generate css classes, which will work with minimal settings. So if you see how to give user more freedom, while not forcing him to position these elements manually, let me know
