### ISSUE TITLE
Don't enforce the offset type

### ISSUE THREAD

**Issue by vabatta** [gvital3230/tailwindcss-tooltip-arrow-after#6]
In https://github.com/gvital3230/tailwindcss-tooltip-arrow-after/blob/master/index.js#L13 you enforce `offset` to be in `px` while in most cases would be useful to use `calc` or `%` values. If you leave the option to pass in a simple string would be great!

**Comment by gvital3230** [comment]
Thanks, you are right, will do it 😄
